### ISSUE TITLE
PYNQ image version

### ISSUE THREAD

**Issue by RezaMehrabian** [yunqu/partial_reconfig_example#1]
Hello,
I have version 2.3. Do you have any solution to run this project on that?

**Comment by yunqu** [comment]
Version 2.3 is based on Xilinx tool version 2018.2; we had some tests before and it did not work. The 2018.2 tool flow does not support PR nicely. Sorry but we will have to use >= 2018.3

**Comment by RezaMehrabian** [comment]
Thank you for your reply. I installed 2018.3. Do you have any other
solution that uses project mode rather than tcl mode? The design processes
for reconfiguration modules and also to get partial bitstream are not clear
in your video.

best regards,

Mohammadreza MEhrabian,

Ph.D. Student, Computer Engineering
School of Computing, Informatics and Decision Systems Engineering
Arizona State University
Tempe, AZ 85281

**Comment by yunqu** [comment]
The make flow is using project mode. If you are talking about GUI vs tcl, I have also tried GUI without success. There are certain steps that have to be done in tcl.

**Comment by RezaMehrabian** [comment]
I meant block diagram mode vs tcl. However, some tcl files are too long. I
think it would be very helpful if we know which ones you wrote and which
ones you made. Without knowing how did you wrote the tcl files, the
tutorial does not work for the person who wants to implement a similar
project.



best regards,

Mohammadreza MEhrabian,

Ph.D. Student, Computer Engineering
School of Computing, Informatics and Decision Systems Engineering
Arizona State University
Tempe, AZ 85281

**Comment by yunqu** [comment]
I don't think the tcl file is long. Sorry there is nothing I can do.

**Comment by RezaMehrabian** [comment]
gpio_pr.tcl
<https://github.com/yunqu/partial_reconfig_example/blob/master/boards/Pynq-Z1/gpio_pr/gpio_pr.tcl>
 ,  led_0.tcl
<https://github.com/yunqu/partial_reconfig_example/blob/master/boards/Pynq-Z1/gpio_pr/led_0.tcl>
, led_5.tcl
<https://github.com/yunqu/partial_reconfig_example/blob/master/boards/Pynq-Z1/gpio_pr/led_5.tcl>
, led_a.tcl
<https://github.com/yunqu/partial_reconfig_example/blob/master/boards/Pynq-Z1/gpio_pr/led_a.tcl>
are
too long. How did you write them? I think by the term "the tcl file" in
your last email you meant create_design.tcl. And true, it is short. What
about the rest files? How did you make them? Did you write or make them by
vivado? If so, when did you make them? It is not clear in your video.

best regards,

Mohammadreza MEhrabian,

Ph.D. Student, Computer Engineering
School of Computing, Informatics and Decision Systems Engineering
Arizona State University
Tempe, AZ 85281

**Comment by yunqu** [comment]
Those files are not hand-written. You can generate them using `write_bd_tcl` command in vivado GUI. 

When you double-click / open your PR region (as a hierarchy block), you are opening it as a very simple block design. Then make change to that block design and use `write_bd_tcl` to generate the tcl file. You will see they are pretty small one (without any PS block in it).

**Comment by RezaMehrabian** [comment]
Thank you so much and sorry for too many questions. I am a beginner in PR
and it is crucial for me to run a project on it. I have two more
questions. Why the notebook example in the Github is different from video
one? You mentioned in the Github it is working with PYNQ image 2.4 version.
I have a 2.3. Is there any other way to run it on PYNQ image 2.3?

best regards,

Mohammadreza MEhrabian,

Ph.D. Student, Computer Engineering
School of Computing, Informatics and Decision Systems Engineering
Arizona State University
Tempe, AZ 85281

**Comment by yunqu** [comment]
Hi, as I said, this is not possible. Please be patient; image v2.4 is going to be out next week. v2.3 is based on Vivado 2018.2 which does not support partial reconfig.
